# Numpy
 Provides efficient way of storing 'numerical data'.

In [3]:
import numpy as np

### Creating an array

In [18]:
np.array([[1,2,3,4],[5,6,7,8]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [19]:
np.zeros((2,3))


array([[0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [21]:
np.empty(4) # uninitailized array

array([7.22769641e+159, 1.22571401e-259, 6.01347002e-154, 5.04038957e+180])

In [23]:
np.eye(3) # also np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [31]:
np.arange(3,13) # similar to range()

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [35]:
np.random.rand(3,4) # random matrix

array([[0.70839393, 0.647962  , 0.32681756, 0.92794998],
       [0.23167128, 0.66326323, 0.48662447, 0.97277159],
       [0.71817751, 0.47619148, 0.9257404 , 0.274086  ]])

### Properties of ndarray

In [39]:
a = np.arange(3,7)
a.ndim #no of dimensions

1

In [41]:
a.shape # shape of array

(4,)

In [42]:
a.dtype

dtype('int32')

In [46]:
a.astype(np.float32) # explicit typecasting

array([3., 4., 5., 6.], dtype=float32)

### Slicing (Indexing & Subsetting)

In [53]:
b = np.array([[2,7,6],[4,8,1]])
b[1,1]

8

In [55]:
b[1,1] = 0 # view on original array, doesn't create a copy. Hence, chagnes are saved.
b

array([[2, 7, 6],
       [4, 0, 1]])

In [59]:
b[1].copy() # creates a copy

array([4, 0, 1])

In [61]:
b[1][2] = 10
b

array([[ 2,  7,  6],
       [ 4,  0, 10]])

In [66]:
c = np.array([4,3,5,2,6,8,1,9])
c[[2,4]] # get elements at given indexes

array([5, 6])

In [67]:
c[[5,-1,-4]]

array([8, 9, 6])

In [71]:
c[3:6]

array([2, 6, 8])

In [74]:
c[c>3] # boolean indexing

array([4, 5, 6, 8, 9])

In [77]:
c[(c==1) | (c > 3)]

array([4, 5, 6, 8, 1, 9])

In [79]:
c[(c > 4) & (c < 7)]

array([5, 6])

In [84]:
d = np.random.rand(5,6)
d

array([[0.81104929, 0.8397617 , 0.98587904, 0.26065152, 0.06742447,
        0.14265294],
       [0.31505875, 0.28548173, 0.23425833, 0.00554757, 0.41163241,
        0.07759809],
       [0.77688582, 0.08207096, 0.90704957, 0.04742238, 0.6534777 ,
        0.36257949],
       [0.85972054, 0.6052267 , 0.51462098, 0.00768526, 0.1475099 ,
        0.73511302],
       [0.39179977, 0.21117291, 0.74986799, 0.8680752 , 0.67916505,
        0.18379314]])

In [90]:
d[[2,4], :3] # slicing with array indexing

array([[0.02782074, 0.51010715, 0.67903362],
       [0.32372159, 0.8653182 , 0.12596291]])

In [93]:
d[[2,4], :3] = np.random.rand(2,3)
d # doesn't crete a copy

array([[0.81104929, 0.8397617 , 0.98587904, 0.26065152, 0.06742447,
        0.14265294],
       [0.31505875, 0.28548173, 0.23425833, 0.00554757, 0.41163241,
        0.07759809],
       [0.14040113, 0.30732889, 0.31320877, 0.04742238, 0.6534777 ,
        0.36257949],
       [0.85972054, 0.6052267 , 0.51462098, 0.00768526, 0.1475099 ,
        0.73511302],
       [0.38549959, 0.34085147, 0.55062039, 0.8680752 , 0.67916505,
        0.18379314]])

### Common Operations

In [106]:
# Transpose
e = np.array([[2,3],[4,0],[7,8]])
e.T # or e.transpose() or e.swapaxes(0,1)

array([[2, 4, 7],
       [3, 0, 8]])

In [107]:
e.swapaxes(0,1)

array([[2, 4, 7],
       [3, 0, 8]])

In [108]:
#Square root
np.sqrt(e)

array([[1.41421356, 1.73205081],
       [2.        , 0.        ],
       [2.64575131, 2.82842712]])

In [109]:
np.where(e > 4, 1, 4)

array([[4, 4],
       [4, 4],
       [1, 1]])

In [110]:
np.where(e > 1) # gives indices of non-zero elements c in first array, r in second array.

(array([0, 0, 1, 2, 2], dtype=int64), array([0, 1, 0, 0, 1], dtype=int64))

In [111]:
np.mean(e, axis = 0)

array([4.33333333, 3.66666667])

In [113]:
np.sum(e, axis = 1)

array([ 5,  4, 15])

### Boolean Array Methods

In [115]:
(e > 0).sum() # number of elements satisfying the condition.

5

In [122]:
e.any() # True if at least one value is true (non-zero in this case)

True

In [123]:
e.all() # True if all values are true (non-zero in this case)

False

### Sorting

In [127]:
np.sort(e)

array([[2, 3],
       [0, 4],
       [7, 8]])

In [129]:
f = np.array([3,2,1,5,4,7,8])
f

array([3, 2, 1, 5, 4, 7, 8])

In [134]:
np.sort(f)

array([1, 2, 3, 4, 5, 7, 8])

In [138]:
g = np.random.rand(2,3)
g

array([[0.49228747, 0.25892218, 0.39878362],
       [0.30299323, 0.20639936, 0.76604736]])

In [141]:
np.sort(g, axis = 0) # 0 - row-wise; 1 - column-wise

array([[0.30299323, 0.20639936, 0.39878362],
       [0.49228747, 0.25892218, 0.76604736]])

#### END